export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const SORT_INGREDIENT: "SORT_INGREDIENT" = "SORT_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";
export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_REQUEST_SUCCESS: "GET_INGREDIENTS_REQUEST_SUCCESS" =
  "GET_INGREDIENTS_REQUEST_SUCCESS";
export const GET_INGREDIENTS_REQUEST_FAILED: "GET_INGREDIENTS_REQUEST_FAILED" =
  "GET_INGREDIENTS_REQUEST_FAILED";
export const ON_CLICK_INGREDIENT: "ON_CLICK_INGREDIENT" = "ON_CLICK_INGREDIENT";
export const DELETE_DETAILS: "DELETE_DETAILS" = "DELETE_DETAILS";
export const GET_ORDER_DETAILS: "GET_ORDER_DETAILS" = "GET_ORDER_DETAILS";
export const GET_ORDER_DETAILS_SUCCESS: "GET_ORDER_DETAILS_SUCCESS" =
  "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAILED: "GET_ORDER_DETAILS_FAILED" =
  "GET_ORDER_DETAILS_FAILED";
export const DELETE_ORDER_DETAILS: "DELETE_ORDER_DETAILS" =
  "DELETE_ORDER_DETAILS";
export const SET_USER: "SET_USER" = "SET_USER";
export const SET_AUTH: "SET_AUTH" = "SET_AUTH";
export const REGISTER_USER: "REGISTER_USER" = "REGISTER_USER";
export const GET_USER: "GET_USER" = "GET_USER";
export const DELETE_USER: "DELETE_USER" = "DELETE_USER";
export const UPDATE_USER: "UPDATE_USER" = "UPDATE_USER";
